// Indice centralizzato dei prodotti per la ricerca
// Generato automaticamente da tutti i site
const productsIndex = [
    { title: "Amazon Basics 14-Piece Knife Block Set", category: "Cucina", site: "site_1", keywords: "amazon basics piece knife block set" },
    { title: "Prodotto Cucina Professionale", category: "Cucina", site: "site_1", keywords: "prodotto cucina professionale" },
    { title: "MITSUMOTO SAKARI Affilacoltelli Professionale", category: "Cucina", site: "site_1", keywords: "mitsumoto sakari affilacoltelli professionale" },
    { title: "Hecef Coltelli da Cucina Professionali 5 Pezzi", category: "Cucina", site: "site_1", keywords: "hecef coltelli cucina professionali pezzi" },
    { title: "Frullatore Immersione Multifunzione", category: "Cucina", site: "site_1", keywords: "frullatore immersione multifunzione" },
    { title: "Bosch Frullatore Immersione MSM24100", category: "Cucina", site: "site_1", keywords: "bosch frullatore immersione msm24100" },
    { title: "Moulinex DD4521 Frullatore Immersione", category: "Cucina", site: "site_1", keywords: "moulinex dd4521 frullatore immersione" },
    { title: "DUNSOO Portaspezie Frigorifero", category: "Cucina", site: "site_1", keywords: "dunsoo portaspezie frigorifero" },
    { title: "Inkbird Bluetooth Termometro Temperatura", category: "Cucina", site: "site_1", keywords: "inkbird bluetooth termometro temperatura" },
    { title: "COSORI Turbo Tower Pro Smart Friggitrice ad Aria", category: "Cucina", site: "site_1", keywords: "cosori turbo tower pro smart friggitrice aria" },
    { title: "COSORI Turbo Blaze Friggitrice ad Aria 6L", category: "Cucina", site: "site_1", keywords: "cosori turbo blaze friggitrice aria" },
    { title: "Ninja Foodi Dual Zone AF300EU", category: "Cucina", site: "site_1", keywords: "ninja foodi dual zone af300eu" },
    { title: "Mova FD10 Pro 6L", category: "Cucina", site: "site_1", keywords: "mova fd10 pro" },
    { title: "Moulinex Easy Fry Precision 4.2L", category: "Cucina", site: "site_1", keywords: "moulinex easy fry precision 4.2l" },
    { title: "Bosch MultiTalent 8 Robot Multifunzione", category: "Cucina", site: "site_1", keywords: "bosch multitalent robot multifunzione" },
    { title: "DeLonghi Magnifica S Macchina per il Caffè", category: "Cucina", site: "site_1", keywords: "delonghi magnifica macchina caffè" },
    { title: "Shavont Valigia Silenziosa con Serratura", category: "Tech", site: "site_10", keywords: "shavont valigia silenziosa serratura" },
    { title: "SMARTBOX Cofanetto Originale Esperienze", category: "Tech", site: "site_10", keywords: "smartbox cofanetto originale esperienze" },
    { title: "Adattatore Universale Worldwide", category: "Tech", site: "site_10", keywords: "adattatore universale worldwide" },
    { title: "FAVIAN Organizer Elettronico Viaggio", category: "Tech", site: "site_10", keywords: "favian organizer elettronico viaggio" },
    { title: "Cirorld Cuscino Cervicale Regolabile", category: "Tech", site: "site_10", keywords: "cirorld cuscino cervicale regolabile" },
    { title: "Ventilatore Regolabile Ricaricabile", category: "Tech", site: "site_10", keywords: "ventilatore regolabile ricaricabile" },
    { title: "Sacchetti Sottovuoto Professionali", category: "Tech", site: "site_10", keywords: "sacchetti sottovuoto professionali" },
    { title: "Daydreamer - Le Ali del Sogno", category: "Libri", site: "site_11", keywords: "daydreamer ali sogno" },
    { title: "Cercando la Storia di Sanem - Prequel DayDreamer", category: "Libri", site: "site_11", keywords: "cercando storia sanem prequel daydreamer" },
    { title: "Le Ali del Sogno - Daydreamer Vol", category: "Libri", site: "site_11", keywords: "ali sogno daydreamer vol" },
    { title: "Pietra Da Massaggio 16Pcs SPA Hot Stone Set", category: "Benessere", site: "site_12", keywords: "pietra massaggio 16pcs spa hot stone set" },
    { title: "20 Pezzi Lava Pietre con Scatola Riscaldante", category: "Benessere", site: "site_12", keywords: "pezzi lava pietre scatola riscaldante" },
    { title: "Gua Sha Viso e Rullo di Giada", category: "Benessere", site: "site_12", keywords: "gua sha viso rullo giada" },
    { title: "Chicco Bombe da Bagno 3 Pezzi POP", category: "Benessere", site: "site_12", keywords: "chicco bombe bagno pezzi pop" },
    { title: "Satin Naturel Cofanetto 4 Bombe da Bagno BIO", category: "Benessere", site: "site_12", keywords: "satin naturel cofanetto bombe bagno bio" },
    { title: "Satin Naturel Cofanetto 6 Bombe da Bagno BIO", category: "Benessere", site: "site_12", keywords: "satin naturel cofanetto bombe bagno bio" },
    { title: "Perlegear Supporto Girevole Estendibile Resistente", category: "Casa", site: "site_14", keywords: "perlegear supporto girevole estendibile resistente" },
    { title: "Utopia Bedding Protettore Impermeabile Ipoallergenico", category: "Casa", site: "site_14", keywords: "utopia bedding protettore impermeabile ipoallergenico" },
    { title: "SONGMICS Pieghevoli Prendisole Poggiatesta Regolabile", category: "Casa", site: "site_14", keywords: "songmics pieghevoli prendisole poggiatesta regolabile" },
    { title: "SONGMICS Scarpiera Organizer Impilabile", category: "Casa", site: "site_14", keywords: "songmics scarpiera organizer impilabile" },
    { title: "Keter Baule marrone resina 116.7x44.7x57", category: "Casa", site: "site_14", keywords: "keter baule marrone resina 116.7x44.7x57" },
    { title: "GUJOIN Zaino Tattico 50L Impermeabile", category: "Viaggi", site: "site_15", keywords: "gujoin zaino tattico 50l impermeabile" },
    { title: "VANKEV Zaino Ryanair 40x20x25 Bagaglio a Mano", category: "Viaggi", site: "site_15", keywords: "vankev zaino ryanair 40x20x25 bagaglio mano" },
    { title: "Aerolite Zaino Ryanair 40x20x25 Bagaglio Massimo", category: "Viaggi", site: "site_15", keywords: "aerolite zaino ryanair 40x20x25 bagaglio massimo" },
    { title: "Google Pixel 8 Pro", category: "Smartphone", site: "site_16", keywords: "google pixel pro" },
    { title: "Samsung Galaxy S24 Ultra", category: "Smartphone", site: "site_16", keywords: "samsung galaxy s24 ultra" },
    { title: "ZTE Axon 40 Ultra", category: "Smartphone", site: "site_16", keywords: "zte axon ultra" },
    { title: "JETech Cover Magnetica Trasparente", category: "Smartphone", site: "site_16", keywords: "jetech cover magnetica trasparente" },
    { title: "Xiaomi REDMI Buds 8 Pro - Cancellazione Attiva Rumore 55dB", category: "Smartphone", site: "site_16", keywords: "xiaomi redmi buds pro cancellazione attiva rumore 55db" },
    { title: "Sennheiser ACCENTUM Open Wireless Earbuds", category: "Smartphone", site: "site_16", keywords: "sennheiser accentum open wireless earbuds" },
    { title: "Tigratigro Caricatore Wireless Mag-Safe 3-in-1", category: "Smartphone", site: "site_16", keywords: "tigratigro caricatore wireless mag safe" },
    { title: "Camicia Elegante Stile Anni '80", category: "Cinema & TV", site: "site_17", keywords: "camicia elegante stile anni '80" },
    { title: "Pantaloni Eleganti in Cotone", category: "Cinema & TV", site: "site_17", keywords: "pantaloni eleganti cotone" },
    { title: "Scialle Elegante con Bottone", category: "Cinema & TV", site: "site_17", keywords: "scialle elegante bottone" },
    { title: "Cravatta Elegante Classica", category: "Cinema & TV", site: "site_17", keywords: "cravatta elegante classica" },
    { title: "Abito Elegante Donna con Tracolla", category: "Cinema & TV", site: "site_17", keywords: "abito elegante donna tracolla" },
    { title: "Gonna Nera Elastica", category: "Cinema & TV", site: "site_17", keywords: "gonna nera elastica" },
    { title: "Zeagoo Abito da Donna con Scollo a V - Stile Bohémien", category: "Cinema & TV", site: "site_17", keywords: "zeagoo abito donna scollo stile bohémien" },
    { title: "iZoeL Costume Hippie Donna Anni 70-80 Completo", category: "Cinema & TV", site: "site_17", keywords: "izoel costume hippie donna anni completo" },
    { title: "Urban Classics Camicia Corduroy TB2414", category: "Cinema & TV", site: "site_17", keywords: "urban classics camicia corduroy tb2414" },
    { title: "Rock Rebel by EMP Camicia con Taschini e Toppe", category: "Cinema & TV", site: "site_17", keywords: "rock rebel emp camicia taschini toppe" },
    { title: "Bigoco Coppola Berretto Piatto Baschi Uomo Regolabile", category: "Cinema & TV", site: "site_17", keywords: "bigoco coppola berretto piatto baschi uomo regolabile" },
    { title: "Sabor Maglia Stranger Things Ufficiale - Hellfire Club Tshirt", category: "Cinema & TV", site: "site_17", keywords: "sabor maglia stranger things ufficiale hellfire club tshirt" },
    { title: "Springrain Cappotto da Uomo Monopetto Misto Lana Colletto Dentellato", category: "Cinema & TV", site: "site_17", keywords: "springrain cappotto uomo monopetto misto lana colletto dentellato" },
    { title: "Peaky Blinders Berretto a 8 Spicchi Lana Tweed Spina di Pesce Blu", category: "Cinema & TV", site: "site_17", keywords: "peaky blinders berretto spicchi lana tweed spina pesce blu" },
    { title: "PROSTEEL Collana Uomo a Catena Barbazzale Cubana Sottile", category: "Cinema & TV", site: "site_17", keywords: "prosteel collana uomo catena barbazzale cubana sottile" },
    { title: "SAGA GIOIELLI® Bracciale Uomo Rondelle Pietre Dure Acciaio (ONICE E CRISTALLI)", category: "Cinema & TV", site: "site_17", keywords: "saga gioielli® bracciale uomo rondelle pietre dure acciaio (onice cristalli)" },
    { title: "Cofanetto Orologio Donna con Set Gioielli (Collana, Anello, Orecchini)", category: "Cinema & TV", site: "site_17", keywords: "cofanetto orologio donna set gioielli (collana anello orecchini)" },
    { title: "Ballandoro Abito Donna Elegante Coprispalle Cerimonia con Pantalone", category: "Cinema & TV", site: "site_17", keywords: "ballandoro abito donna elegante coprispalle cerimonia pantalone" },
    { title: "YYNUDA Tailleur con Pantalone Donna Stile Manageriale", category: "Cinema & TV", site: "site_17", keywords: "yynuda tailleur pantalone donna stile manageriale" },
    { title: "Allthemen Abito da Uomo Elastico 3 Pezzi Completo Slim Fit Formale (Blazer Pantaloni Gilet)", category: "Cinema & TV", site: "site_17", keywords: "allthemen abito uomo elastico pezzi completo slim fit formale (blazer pantaloni gilet)" },
    { title: "Tod's Women's Platform Loafer in Blue Leather with Mask", category: "Cinema & TV", site: "site_17", keywords: "tod's women's platform loafer blue leather with mask" },
    { title: "Women's Knitted Vest, Women's Sleeveless V-Neck Pullover Sweaters", category: "Cinema & TV", site: "site_17", keywords: "women's knitted vest women's sleeveless neck pullover sweaters" },
    { title: "Generico Giacche Eleganti Donna Nero Contrasto Autunnali", category: "Cinema & TV", site: "site_17", keywords: "generico giacche eleganti donna nero contrasto autunnali" },
    { title: "Fallout - Saluti da Maglietta", category: "Cinema & TV", site: "site_17", keywords: "fallout saluti maglietta" },
    { title: "Fallout - Maglietta Nuka Cola", category: "Cinema & TV", site: "site_17", keywords: "fallout maglietta nuka cola" },
    { title: "Fallout - Cucciolo di Cane Maglietta", category: "Cinema & TV", site: "site_17", keywords: "fallout cucciolo cane maglietta" },
    { title: "Shogun Tramonto Maglietta", category: "Cinema & TV", site: "site_17", keywords: "shogun tramonto maglietta" },
    { title: "Tokugawa Clan Crest Maglietta", category: "Cinema & TV", site: "site_17", keywords: "tokugawa clan crest maglietta" },
    { title: "Bridgerton Regency Dress", category: "Cinema & TV", site: "site_17", keywords: "bridgerton regency dress" },
    { title: "Money Heist Bella Ciao Maglietta", category: "Cinema & TV", site: "site_17", keywords: "money heist bella ciao maglietta" },
    { title: "Elisabetta II Queen Platinum Maglietta", category: "Cinema & TV", site: "site_17", keywords: "elisabetta queen platinum maglietta" },
    { title: "The Witcher Kaer Morhen Maglietta", category: "Cinema & TV", site: "site_17", keywords: "the witcher kaer morhen maglietta" },
    { title: "Witcher Logo Silhouette Felpa", category: "Cinema & TV", site: "site_17", keywords: "witcher logo silhouette felpa" },
    { title: "Witcher Medallion T-Shirt", category: "Cinema & TV", site: "site_17", keywords: "witcher medallion shirt" },
    { title: "CMTOP Abito Donna Girocollo", category: "Moda Donna", site: "site_18", keywords: "cmtop abito donna girocollo" },
    { title: "Enmain Abito Donna Maniche Corte", category: "Moda Donna", site: "site_18", keywords: "enmain abito donna maniche corte" },
    { title: "LIAOPUFUS Blazer Slim Fit Maniche Lunghe", category: "Moda Donna", site: "site_18", keywords: "liaopufus blazer slim fit maniche lunghe" },
    { title: "Shownicer Camicia Lino Donna", category: "Moda Donna", site: "site_18", keywords: "shownicer camicia lino donna" },
    { title: "Amazon Essentials Leggings Stretch", category: "Moda Donna", site: "site_18", keywords: "amazon essentials leggings stretch" },
    { title: "Amropi Set Felpa Foderata + Pantaloni Jogging", category: "Moda Donna", site: "site_18", keywords: "amropi set felpa foderata pantaloni jogging" },
    { title: "Beauty Women Maglione Invernale Elegante", category: "Moda Donna", site: "site_18", keywords: "beauty women maglione invernale elegante" },
    { title: "Mogidol Abito Estivo in Raso con Spalline Sottili", category: "Moda Donna", site: "site_18", keywords: "mogidol abito estivo raso spalline sottili" },
    { title: "Sukiglam Abito Asimmetrico Monospalla Increspato", category: "Moda Donna", site: "site_18", keywords: "sukiglam abito asimmetrico monospalla increspato" },
    { title: "VALORIALUXE Abito Cerimonia Lungo in Tulle con Balze", category: "Moda Donna", site: "site_18", keywords: "valorialuxe abito cerimonia lungo tulle balze" },
    { title: "Natura Prime Passiflora Rilassamento", category: "Benessere & Relax", site: "site_19", keywords: "natura prime passiflora rilassamento" },
    { title: "HIQILI 100ml Olio Essenziale Lavanda", category: "Benessere & Relax", site: "site_19", keywords: "hiqili 100ml olio essenziale lavanda" },
    { title: "12 Tipi Maschera Viso Idratante in Tessuto", category: "Benessere & Relax", site: "site_19", keywords: "tipi maschera viso idratante tessuto" },
    { title: "Corine Farme Natural Anti-Stress Vaniglia", category: "Benessere & Relax", site: "site_19", keywords: "corine farme natural anti stress vaniglia" },
    { title: "Tapo Presa Smart con Monitoraggio", category: "Smart Home", site: "site_2", keywords: "tapo presa smart monitoraggio" },
    { title: "Amazon Basics Presa Intelligente", category: "Smart Home", site: "site_2", keywords: "amazon basics presa intelligente" },
    { title: "TP-Link Tapo P105 Presa Smart", category: "Smart Home", site: "site_2", keywords: "link tapo p105 presa smart" },
    { title: "Echo Dot Max Alexa", category: "Smart Home", site: "site_2", keywords: "echo dot max alexa" },
    { title: "Broadlink Telecomando Universale Infrarossi", category: "Smart Home", site: "site_2", keywords: "broadlink telecomando universale infrarossi" },
    { title: "Telecomando Universale Infrarossi Condizionatore", category: "Smart Home", site: "site_2", keywords: "telecomando universale infrarossi condizionatore" },
    { title: "Ring Intercom di Amazon", category: "Smart Home", site: "site_2", keywords: "ring intercom amazon" },
    { title: "TMEZON Videocitofono Monofamiliare", category: "Smart Home", site: "site_2", keywords: "tmezon videocitofono monofamiliare" },
    { title: "BOIFUN Videocitofono WiFi 2K", category: "Smart Home", site: "site_2", keywords: "boifun videocitofono wifi" },
    { title: "TP-Link Telecamera Videocamera Sorveglianza", category: "Smart Home", site: "site_2", keywords: "link telecamera videocamera sorveglianza" },
    { title: "TP-Link Tapo C520WS Telecamera Esterno", category: "Smart Home", site: "site_2", keywords: "link tapo c520ws telecamera esterno" },
    { title: "TP-Link Tapo C210 Telecamera Interno", category: "Smart Home", site: "site_2", keywords: "link tapo c210 telecamera interno" },
    { title: "Allthemen Blazer Nero Slim Fit Elegante", category: "Moda Uomo", site: "site_20", keywords: "allthemen blazer nero slim fit elegante" },
    { title: "Runcati Camicia Lino Maniche Corte", category: "Moda Uomo", site: "site_20", keywords: "runcati camicia lino maniche corte" },
    { title: "Jack & Jones Jeans Slim Fit Denim", category: "Moda Uomo", site: "site_20", keywords: "jack jones jeans slim fit denim" },
    { title: "Carrera Jeans 000700_01021", category: "Moda Uomo", site: "site_20", keywords: "carrera jeans 000700_01021" },
    { title: "TEAMMAO Cintura in Pelle Uomo", category: "Moda Uomo", site: "site_20", keywords: "teammao cintura pelle uomo" },
    { title: "COOFANDY Camicia Uomo Maniche Corte", category: "Moda Uomo", site: "site_20", keywords: "coofandy camicia uomo maniche corte" },
    { title: "Orologio Militare Analogico", category: "Moda Uomo", site: "site_20", keywords: "orologio militare analogico" },
    { title: "Songmics Scatola Porta Orologi", category: "Moda Uomo", site: "site_20", keywords: "songmics scatola porta orologi" },
    { title: "ZENOTTIC Occhiali da Sole Geometrici", category: "Accessori", site: "site_21", keywords: "zenottic occhiali sole geometrici" },
    { title: "VONMELLI Cintura in Pelle Marrone", category: "Accessori", site: "site_21", keywords: "vonmelli cintura pelle marrone" },
    { title: "FaithHeart Bracciale a Catena", category: "Accessori", site: "site_21", keywords: "faithheart bracciale catena" },
    { title: "Anello Sigillo in Acciaio Inossidabile", category: "Accessori", site: "site_21", keywords: "anello sigillo acciaio inossidabile" },
    { title: "Orologio Militare Analogico Impermeabile", category: "Accessori", site: "site_21", keywords: "orologio militare analogico impermeabile" },
    { title: "Avatar Fuoco e Cenere BD", category: "DVD & Blu-ray", site: "site_22", keywords: "avatar fuoco cenere" },
    { title: "Dylan - Dennis Haysbert, Xavier McAdams", category: "DVD & Blu-ray", site: "site_22", keywords: "dylan dennis haysbert xavier mcadams" },
    { title: "Signore degli Anelli Trilogia Rimasterizzata", category: "DVD & Blu-ray", site: "site_22", keywords: "signore degli anelli trilogia rimasterizzata" },
    { title: "Matrix Film Collection Ultra HD Blu-Ray", category: "DVD & Blu-ray", site: "site_22", keywords: "matrix film collection ultra blu ray" },
    { title: "Michael Steelbook 4K UHD Blu-ray", category: "DVD & Blu-ray", site: "site_22", keywords: "michael steelbook uhd blu ray" },
    { title: "DUNE: PARTE DUE 4K UHD", category: "DVD & Blu-ray", site: "site_22", keywords: "dune: parte due uhd" },
    { title: "Rocky Saga (Box 6 Br)", category: "DVD & Blu-ray", site: "site_22", keywords: "rocky saga (box br)" },
    { title: "Shining - Extended Edition (2 Blu Ray)", category: "DVD & Blu-ray", site: "site_22", keywords: "shining extended edition blu ray)" },
    { title: "Batman BS Blu-Ray", category: "DVD & Blu-ray", site: "site_22", keywords: "batman blu ray" },
    { title: "Inception Blu-Ray Nuovo", category: "DVD & Blu-ray", site: "site_22", keywords: "inception blu ray nuovo" },
    { title: "Gran Torino Blu-ray Nuovo", category: "DVD & Blu-ray", site: "site_22", keywords: "gran torino blu ray nuovo" },
    { title: "Interstellar 4K UHD Blu-Ray Nuovo", category: "DVD & Blu-ray", site: "site_22", keywords: "interstellar uhd blu ray nuovo" },
    { title: "Il Gladiatore 4K UHD Blu-Ray Nuovo", category: "DVD & Blu-ray", site: "site_22", keywords: "gladiatore uhd blu ray nuovo" },
    { title: "LEONE Rashguard Legionarivs", category: "Fitness", site: "site_3", keywords: "leone rashguard legionarivs" },
    { title: "Set Attrezzi Home Gym Professionale", category: "Fitness", site: "site_3", keywords: "set attrezzi home gym professionale" },
    { title: "Tappetino Yoga Spessore Antiscivolo", category: "Fitness", site: "site_3", keywords: "tappetino yoga spessore antiscivolo" },
    { title: "Under Armour Comp T-Shirt", category: "Fitness", site: "site_3", keywords: "under armour comp shirt" },
    { title: "TECEUM NUOVO 2023 Yoga Strap", category: "Fitness", site: "site_3", keywords: "teceum nuovo 2023 yoga strap" },
    { title: "unycos Manubri Antiscivolo Disponibili", category: "Fitness", site: "site_3", keywords: "unycos manubri antiscivolo disponibili" },
    { title: "RE Manubri Regolabili con Chiusure", category: "Fitness", site: "site_3", keywords: "manubri regolabili chiusure" },
    { title: "Joma Nobel T-Shirt Allenamento", category: "Fitness", site: "site_3", keywords: "joma nobel shirt allenamento" },
    { title: "Panathletic Elastici Fitness Set Bande", category: "Fitness", site: "site_3", keywords: "panathletic elastici fitness set bande" },
    { title: "YOGATI Tappetino Yoga Antiscivolo con Allineamento", category: "Fitness", site: "site_3", keywords: "yogati tappetino yoga antiscivolo allineamento" },
    { title: "PUMA Teamgoal Tee Magliette Uomo", category: "Fitness", site: "site_3", keywords: "puma teamgoal tee magliette uomo" },
    { title: "Amazon Basics Coppia di Manubri in Neoprene", category: "Fitness", site: "site_3", keywords: "amazon basics coppia manubri neoprene" },
    { title: "FIFlying Vialetto Inossidabile per Giardino", category: "Giardinaggio", site: "site_4", keywords: "fiflying vialetto inossidabile giardino" },
    { title: "Decorazione Giardino Impermeabile per Vialetto", category: "Giardinaggio", site: "site_4", keywords: "decorazione giardino impermeabile vialetto" },
    { title: "Kit ORTO-URBANO Large - Il tuo orto sul balcone", category: "Giardinaggio", site: "site_4", keywords: "kit orto urbano large tuo orto sul balcone" },
    { title: "Kit Orto-Urbano Small - Il tuo orto sul balcone", category: "Giardinaggio", site: "site_4", keywords: "kit orto urbano small tuo orto sul balcone" },
    { title: "KIT per orto sul balcone BASILICO - ORTO BOX", category: "Giardinaggio", site: "site_4", keywords: "kit orto sul balcone basilico orto box" },
    { title: "Worx WG749E WORX Tagliaerba Nero", category: "Giardinaggio", site: "site_4", keywords: "worx wg749e worx tagliaerba nero" },
    { title: "STOCKER Nebulizzatore Antizanzare con Installazione Alimentatore", category: "Giardinaggio", site: "site_4", keywords: "stocker nebulizzatore antizanzare installazione alimentatore" },
    { title: "Spontex 153107 Guanti Silky Media", category: "Giardinaggio", site: "site_4", keywords: "spontex 153107 guanti silky media" },
    { title: "Sacchetto l'irrigazione sacchetto resistente irrigazione", category: "Giardinaggio", site: "site_4", keywords: "sacchetto l'irrigazione sacchetto resistente irrigazione" },
    { title: "Aqua-Control C4099O Programmatore d'irrigazione", category: "Giardinaggio", site: "site_4", keywords: "aqua control c4099o programmatore d'irrigazione" },
    { title: "Multipresa Interruttori Indipendenti Salvaspazio Sovratensione", category: "Ufficio", site: "site_5", keywords: "multipresa interruttori indipendenti salvaspazio sovratensione" },
    { title: "NEWYES Cartellina conferenze Portafoglio", category: "Ufficio", site: "site_5", keywords: "newyes cartellina conferenze portafoglio" },
    { title: "HISDERN Panciotto Elegante Vintage in Tweed", category: "Ufficio", site: "site_5", keywords: "hisdern panciotto elegante vintage tweed" },
    { title: "HISDERN Gilet Nero Formale da Cerimonia", category: "Ufficio", site: "site_5", keywords: "hisdern gilet nero formale cerimonia" },
    { title: "Hisdern Cravatta con Fazzoletto Rosso", category: "Ufficio", site: "site_5", keywords: "hisdern cravatta fazzoletto rosso" },
    { title: "Hisdern Abito in Cotone Solido Formale", category: "Ufficio", site: "site_5", keywords: "hisdern abito cotone solido formale" },
    { title: "Macchina Fotografica Digitale per Principianti", category: "Fotografia", site: "site_6", keywords: "macchina fotografica digitale principianti" },
    { title: "Luce Magnetica per Fotocamera Ricaricabile", category: "Fotografia", site: "site_6", keywords: "luce magnetica fotocamera ricaricabile" },
    { title: "RISEOFLE Treppiede Smartphone con Telecomando", category: "Fotografia", site: "site_6", keywords: "riseofle treppiede smartphone telecomando" },
    { title: "Treppiede Smartphone Cavalletto con Telecomando", category: "Fotografia", site: "site_6", keywords: "treppiede smartphone cavalletto telecomando" },
    { title: "Lamicall Treppiede Smartphone Flessibile con Telecomando", category: "Fotografia", site: "site_6", keywords: "lamicall treppiede smartphone flessibile telecomando" },
    { title: "AURIVEE Montatura Posteriore Smartphone con Luminosità Regolabile", category: "Fotografia", site: "site_6", keywords: "aurivee montatura posteriore smartphone luminosità regolabile" },
    { title: "Teleprompter con Treppiede e Telecomando per Smartphone", category: "Fotografia", site: "site_6", keywords: "teleprompter treppiede telecomando smartphone" },
    { title: "Insta360 Snap Schermo Selfie con Luce Integrata", category: "Fotografia", site: "site_6", keywords: "insta360 snap schermo selfie luce integrata" },
    { title: "Fontanella per Gatti senza Fili Ricaricabile", category: "Pet Care", site: "site_7", keywords: "fontanella gatti senza fili ricaricabile" },
    { title: "PETKIT Pura Max 2 Lettiera Gatto Autopulente", category: "Pet Care", site: "site_7", keywords: "petkit pura max lettiera gatto autopulente" },
    { title: "Fockety Mangiatoia Automatica per Gatti", category: "Pet Care", site: "site_7", keywords: "fockety mangiatoia automatica gatti" },
    { title: "PETCUTE Zaino Per Gatti Trasparente", category: "Pet Care", site: "site_7", keywords: "petcute zaino gatti trasparente" },
    { title: "HaoAMZ Toilette Automatica per Gatti 50L", category: "Pet Care", site: "site_7", keywords: "haoamz toilette automatica gatti 50l" },
    { title: "Lettiera Gatto Autopulente 65L con APP", category: "Pet Care", site: "site_7", keywords: "lettiera gatto autopulente 65l app" },
    { title: "Pecute Guinzaglio per Cani Retrattile 5m", category: "Pet Care", site: "site_7", keywords: "pecute guinzaglio cani retrattile" },
    { title: "Makife Guinzaglio Retrattile per Cani 5m", category: "Pet Care", site: "site_7", keywords: "makife guinzaglio retrattile cani" },
    { title: "Guinzaglio Retrattile Allungabile 5M con Impugnatura Antiscivolo", category: "Pet Care", site: "site_7", keywords: "guinzaglio retrattile allungabile impugnatura antiscivolo" },
    { title: "Pecute Guinzaglio Retrattile per Cani", category: "Pet Care", site: "site_7", keywords: "pecute guinzaglio retrattile cani" },
    { title: "Criceto Ruota Silenziosa per Esercizio", category: "Pet Care", site: "site_7", keywords: "criceto ruota silenziosa esercizio" },
    { title: "BUCATSTATE Criceto Ruota Silenziosa 32cm", category: "Pet Care", site: "site_7", keywords: "bucatstate criceto ruota silenziosa 32cm" },
    { title: "Nobleza Acquario 30L Completo con LED", category: "Pet Care", site: "site_7", keywords: "nobleza acquario 30l completo led" },
    { title: "AQPET Acquario per Pesci Tropicali Completo", category: "Pet Care", site: "site_7", keywords: "aqpet acquario pesci tropicali completo" },
    { title: "One Glass Aquarium Completo con Accessori", category: "Pet Care", site: "site_7", keywords: "one glass aquarium completo accessori" },
    { title: "FRONTLINE Combo 6 Pipette per Gatti", category: "Pet Care", site: "site_7", keywords: "frontline combo pipette gatti" },
    { title: "FRONTLINE Spot On 4 Pipette per Gatti", category: "Pet Care", site: "site_7", keywords: "frontline spot pipette gatti" },
    { title: "FRONTLINE Combo 3 Pipette per Gatti", category: "Pet Care", site: "site_7", keywords: "frontline combo pipette gatti" },
    { title: "Tiragraffi Multilivello 145cm", category: "Pet Care", site: "site_7", keywords: "tiragraffi multilivello 145cm" },
    { title: "Amazon Basics Tiragraffi Albero Grande", category: "Pet Care", site: "site_7", keywords: "amazon basics tiragraffi albero grande" },
    { title: "Beltom Tiragraffi Giochi Palestra", category: "Pet Care", site: "site_7", keywords: "beltom tiragraffi giochi palestra" },
    { title: "Amazon Caffè Espresso Crema", category: "Caffè", site: "site_8", keywords: "amazon caffè espresso crema" },
    { title: "Kit Pulizia Macchina da Caffè", category: "Caffè", site: "site_8", keywords: "kit pulizia macchina caffè" },
    { title: "WoldoClean 2in1 Descaler", category: "Caffè", site: "site_8", keywords: "woldoclean 2in1 descaler" },
    { title: "Universal Completing Accessories Nespresso", category: "Caffè", site: "site_8", keywords: "universal completing accessories nespresso" },
    { title: "Nespresso Decalcificante Originale", category: "Caffè", site: "site_8", keywords: "nespresso decalcificante originale" },
    { title: "ZORTVUL Spazzolino Macchina Macinacaffè", category: "Caffè", site: "site_8", keywords: "zortvul spazzolino macchina macinacaffè" },
    { title: "Aquafloow Kit DeLonghi", category: "Caffè", site: "site_8", keywords: "aquafloow kit delonghi" },
    { title: "MSI Monitor Gaming G255F", category: "Gaming", site: "site_9", keywords: "msi monitor gaming g255f" },
    { title: "Vibox Gaming PC Ryzen", category: "Gaming", site: "site_9", keywords: "vibox gaming ryzen" },
    { title: "Samsung 970 EVO Plus SSD 1TB NVMe M.2", category: "Gaming", site: "site_9", keywords: "samsung 970 evo plus ssd 1tb nvme m.2" },
    { title: "WD Black SN850X SSD 1TB NVMe M.2", category: "Gaming", site: "site_9", keywords: "black sn850x ssd 1tb nvme m.2" },
    { title: "Logitech G502 Lightspeed Wireless", category: "Gaming", site: "site_9", keywords: "logitech g502 lightspeed wireless" },
    { title: "Razer DeathAdder Essential", category: "Gaming", site: "site_9", keywords: "razer deathadder essential" },
    { title: "Gaming Programmabili Illuminazione Multicolore", category: "Gaming", site: "site_9", keywords: "gaming programmabili illuminazione multicolore" },
    { title: "HyperX Cloud II", category: "Gaming", site: "site_9", keywords: "hyperx cloud" },
    { title: "Razer Kraken", category: "Gaming", site: "site_9", keywords: "razer kraken" },
    { title: "Trust Gaming", category: "Gaming", site: "site_9", keywords: "trust gaming" },
    { title: "ASUS GT-AXE11000", category: "Gaming", site: "site_9", keywords: "asus axe11000" },
    { title: "TP-Link Archer AX72 Pro", category: "Gaming", site: "site_9", keywords: "link archer ax72 pro" },
    { title: "TP-Link AC1200 Archer C6", category: "Gaming", site: "site_9", keywords: "link ac1200 archer" },
    { title: "ASUS FreeSync", category: "Gaming", site: "site_9", keywords: "asus freesync" },
    { title: "LG UltraGear", category: "Gaming", site: "site_9", keywords: "ultragear" },
    { title: "Corsair Tastiera magnetica meccanica", category: "Gaming", site: "site_9", keywords: "corsair tastiera magnetica meccanica" },
    { title: "Razer BlackWidow Green Switch", category: "Gaming", site: "site_9", keywords: "razer blackwidow green switch" },
    { title: "Redragon meccanica Bluetooth", category: "Gaming", site: "site_9", keywords: "redragon meccanica bluetooth" },
];

// Funzione per cercare prodotti
function searchProducts(query) {
    const lowerQuery = query.toLowerCase().trim();
    if (lowerQuery === '') return [];
    
    return productsIndex.filter(product => {
        const titleMatch = product.title.toLowerCase().includes(lowerQuery);
        const keywordsMatch = product.keywords.toLowerCase().includes(lowerQuery);
        const categoryMatch = product.category.toLowerCase().includes(lowerQuery);
        
        return titleMatch || keywordsMatch || categoryMatch;
    });
}
